# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyBookshelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyBookshelf

    pod 'SnapKit', '~> 5.0.0'
    pod 'ObjectMapper', '~> 3.5'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
    pod 'Alamofire', '~> 5.5'

  target 'MyBookshelfTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyBookshelfUITests' do
    # Pods for testing
  end

end
